#!/usr/bin/env python3
"""bin2s.py — embed a binary file as a GNU-assembler byte array: a portable, dependency-free
stand-in for devkitPro's `bin2s`, so the PSP EBOOT build needs only pspdev (no second SDK).

Emits the same symbols bin2s does — `<name>`, `<name>_end`, `<name>_size` — where `<name>` is
the input's basename with every non-alphanumeric character replaced by `_` (so `platformer.phxp`
-> `platformer_phxp`, matching the `extern` the entry point declares). Writes the .s to stdout.

Usage:  bin2s.py <input-file>  > out.s
"""
import os
import sys


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: bin2s.py <file>\n")
        return 2
    path = sys.argv[1]
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError as e:
        sys.stderr.write(f"bin2s: cannot read {path}: {e}\n")
        return 1

    name = "".join(c if c.isalnum() else "_" for c in os.path.basename(path))
    w = sys.stdout.write
    w("/* Generated by bin2s.py — do not edit */\n")
    w(f'\t.section .rodata.{name}, "a"\n\t.balign 4\n')
    w(f"\t.global {name}\n{name}:\n")
    for i in range(0, len(data), 16):
        w("\t.byte " + ", ".join("%3d" % b for b in data[i:i + 16]) + "\n")
    w(f"\t.global {name}_end\n\t.balign 4\n{name}_end:\n\n")
    w(f"\t.global {name}_size\n\t.balign 4\n{name}_size: .int {len(data)}\n")
    # Mark the stack non-executable on ELF targets (PSP + host), matching devkitPro's output.
    w('\n#if defined(__linux__) && defined(__ELF__)\n'
      '.section .note.GNU-stack,"",%progbits\n#endif\n')
    return 0


if __name__ == "__main__":
    sys.exit(main())
