#!/usr/bin/env python3
"""Regenerate tools/common/jetbrains_mono_data.h from fonts/JetBrainsMono-ASCII.ttf.

The .ttf is JetBrains Mono Regular (https://github.com/JetBrains/JetBrainsMono, OFL 1.1) subset to
printable ASCII with:

    python -m fontTools.subset JetBrainsMono-Regular.ttf --unicodes=U+0020-007E --layout-features= \
        --no-hinting --name-IDs='*' --notdef-outline --output-file=fonts/JetBrainsMono-ASCII.ttf

Run from tools/common:  python gen_font_data.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "fonts", "JetBrainsMono-ASCII.ttf")
DST = os.path.join(HERE, "jetbrains_mono_data.h")

data = open(SRC, "rb").read()
rows = ["    " + ",".join("0x%02X" % b for b in data[i:i + 24]) + "," for i in range(0, len(data), 24)]
out = """// tools/common/jetbrains_mono_data.h — GENERATED by tools/common/gen_font_data.py from
// fonts/JetBrainsMono-ASCII.ttf (JetBrains Mono Regular, subset to printable ASCII U+0020..U+007E, no
// hinting/layout tables). Copyright 2020 The JetBrains Mono Project Authors, SIL Open Font License 1.1
// (fonts/JetBrainsMono-OFL.txt). Do not edit by hand.
#ifndef PHX_TOOLS_JETBRAINS_MONO_DATA_H
#define PHX_TOOLS_JETBRAINS_MONO_DATA_H

#include <cstddef>

namespace phxtool {

inline constexpr unsigned char kJetBrainsMonoAscii[] = {
%s
};
inline constexpr size_t kJetBrainsMonoAsciiSize = sizeof(kJetBrainsMonoAscii);

} // namespace phxtool
#endif
""" % "\n".join(rows)
with open(DST, "w", newline="\n", encoding="utf-8") as f:
    f.write(out)
print("wrote", DST, len(data), "bytes")
